services:
  app:
    image: ghcr.io/whi-tw/arunapi/arunapi:latest
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      REDIS_URL: redis://redis:6379
  redis:
    image: redis:alpine
