{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-redis
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.redis.servicePort }}
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end }}
